version: "3"
name: imgdb

services:
  database:
    image: neo4j
    container_name: neo4j
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - C:/neo4j/data:/data
      - C:/neo4j/logs:/logs
      - C:/neo4j/import:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/test
      
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    image: imgdb-api-server
    depends_on:
      - database

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.client
    image: imgdb-frontend
    ports:
      - "3000:80"
    depends_on:
      - api

  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile.scheduler
    image: imgdb-scheduler
    depends_on:
      - api
      - database
